name: Deploy Theme

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build assets
      uses: elstudio/actions-js-build/build@v2
      with:
        args: run prod
        
    - name: Deploy Ghost Theme
      uses: TryGhost/action-deploy-theme@v1.2.0
      with:
        api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
        api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
        exclude: node_modules
